soc,user_random,user_random
soc,user_uart,user_uart
soc,user_uart1,user_uart1
soc,user_risc_boot,user_risc_boot
soc,user_qspi,user_qspi
soc,user_sspi,user_sspi
soc,user_i2cm,user_i2cm
soc,user_usb,user_usb
soc,user_gpio,user_gpio
soc,user_basic,user_basic
soc,user_spi_isp,user_spi_isp
soc,user_timer,user_timer
soc,user_uart_master,user_uart_master
soc,user_sram_exec,user_sram_exec
soc,user_cache_bypass,user_cache_bypass
soc,user_pwm,user_pwm
soc,user_sema,user_sema
full_chip,risc_boot,risc_boot
full_chip,uart_master_test1,uart_master_test1
full_chip,uart_master_test2,uart_master_test2
full_chip,wb_port,wb_port
arduino,arduino_arrays,arduino_arrays
arduino,arduino_risc_boot,arduino_risc_boot
arduino,arduino_timer_intr,arduino_timer_intr
arduino,arduino_ascii_table,arduino_ascii_table
arduino,arduino_gpio_intr,arduino_gpio_intr
arduino,arduino_i2c_wr_rd,arduino_i2c_wr_rd
arduino,arduino_string,arduino_string
arduino,arduino_ws281x,arduino_ws281x
arduino,arduino_character_analysis,arduino_character_analysis
arduino,arduino_hello_world,arduino_hello_world
arduino,arduino_multi_serial,arduino_multi_serial
arduino,arduino_switchCase2,arduino_switchCase2
soc,user_aes_core,user_aes_core
soc,user_fpu_core,user_fpu_core
soc,user_aes,user_aes
soc,user_rtc,user_rtc
soc,user_ir_tx,user_ir_tx
soc,user_ir_rx,user_ir_rx
soc,step_motor_controller,step_motor_controller
caravel,caravel_hkspi,caravel_hkspi
soc,user_qspis,user_qspis
soc,user_cpu_clkgate,user_cpu_clkgate
arduino,arduino_digital_port_control,arduino_digital_port_control
arduino,arduino_i2c_scaner,arduino_i2c_scaner
mcore,user_mcore_test1,user_mcore_test1
mcore,user_mcore_test2,user_mcore_test2
arduino,arduino_line_follower,arduino_line_follower
arduino,arduino_gpio_output,arduino_gpio_output
arduino,arduino_gpio_input,arduino_gpio_input
arduino,arduino_sprintf,arduino_sprintf
riscv,add,riscv_regress
riscv,addi,riscv_regress
riscv,and,riscv_regress
riscv,andi,riscv_regress
riscv,auipc,riscv_regress
riscv,beq,riscv_regress
riscv,bge,riscv_regress
riscv,bgeu,riscv_regress
riscv,blt,riscv_regress
riscv,bltu,riscv_regress
riscv,bne,riscv_regress
riscv,csr,riscv_regress
riscv,fence_i,riscv_regress
riscv,illegal,riscv_regress
riscv,jal,riscv_regress
riscv,jalr,riscv_regress
riscv,lb,riscv_regress
riscv,lbu,riscv_regress
riscv,lh,riscv_regress
riscv,lhu,riscv_regress
riscv,lui,riscv_regress
riscv,lw,riscv_regress
riscv,ma_addr,riscv_regress
riscv,ma_fetch,riscv_regress
riscv,mcsr,riscv_regress
riscv,or,riscv_regress
riscv,ori,riscv_regress
riscv,sb,riscv_regress
riscv,sbreak,riscv_regress
riscv,scall,riscv_regress
riscv,sh,riscv_regress
riscv,shamt,riscv_regress
riscv,simple,riscv_regress
riscv,sll,riscv_regress
riscv,slli,riscv_regress
riscv,slt,riscv_regress
riscv,slti,riscv_regress
riscv,sltiu,riscv_regress
riscv,sltu,riscv_regress
riscv,sra,riscv_regress
riscv,srai,riscv_regress
riscv,srl,riscv_regress
riscv,srli,riscv_regress
riscv,sub,riscv_regress
riscv,sw,riscv_regress
riscv,xor,riscv_regress
riscv,xori,riscv_regress
riscv,div,riscv_regress
riscv,divu,riscv_regress
riscv,mul,riscv_regress
riscv,mulh,riscv_regress
riscv,mulhsu,riscv_regress
riscv,mulhu,riscv_regress
riscv,rem,riscv_regress
riscv,remu,riscv_regress
riscv,rvc,riscv_regress
riscv,compliance_I-ADDI-01,riscv_regress
riscv,compliance_I-RF_x0-01,riscv_regress
riscv,compliance_I-ADD-01,riscv_regress
riscv,compliance_I-SLLI-01,riscv_regress
riscv,compliance_I-SLT-01,riscv_regress
riscv,compliance_I-ORI-01,riscv_regress
riscv,compliance_I-SUB-01,riscv_regress
riscv,compliance_I-LH-01,riscv_regress
riscv,compliance_I-XORI-01,riscv_regress
riscv,compliance_I-JAL-01,riscv_regress
riscv,compliance_I-ENDIANESS-01,riscv_regress
riscv,compliance_I-BNE-01,riscv_regress
riscv,compliance_I-RF_width-01,riscv_regress
riscv,compliance_I-LBU-01,riscv_regress
riscv,compliance_I-IO-01,riscv_regress
riscv,compliance_I-SLL-01,riscv_regress
riscv,compliance_I-SLTI-01,riscv_regress
riscv,compliance_I-BLT-01,riscv_regress
riscv,compliance_I-BGE-01,riscv_regress
riscv,compliance_I-SRLI-01,riscv_regress
riscv,compliance_I-DELAY_SLOTS-01,riscv_regress
riscv,compliance_I-LHU-01,riscv_regress
riscv,compliance_I-RF_size-01,riscv_regress
riscv,compliance_I-OR-01,riscv_regress
riscv,compliance_I-SH-01,riscv_regress
riscv,compliance_I-LW-01,riscv_regress
riscv,compliance_I-ANDI-01,riscv_regress
riscv,compliance_I-SW-01,riscv_regress
riscv,compliance_I-BLTU-01,riscv_regress
riscv,compliance_I-SRAI-01,riscv_regress
riscv,compliance_I-SRA-01,riscv_regress
riscv,compliance_I-SLTU-01,riscv_regress
riscv,compliance_I-NOP-01,riscv_regress
riscv,compliance_I-BEQ-01,riscv_regress
riscv,compliance_I-LUI-01,riscv_regress
riscv,compliance_I-SLTIU-01,riscv_regress
riscv,compliance_I-JALR-01,riscv_regress
riscv,compliance_I-AUIPC-01,riscv_regress
riscv,compliance_I-BGEU-01,riscv_regress
riscv,compliance_I-XOR-01,riscv_regress
riscv,compliance_I-AND-01,riscv_regress
riscv,compliance_I-SRL-01,riscv_regress
riscv,compliance_I-SB-01,riscv_regress
riscv,compliance_I-LB-01,riscv_regress
riscv,compliance_I-CSRRSI-01,riscv_regress
riscv,compliance_I-CSRRCI-01,riscv_regress
riscv,compliance_I-CSRRWI-01,riscv_regress
riscv,compliance_I-CSRRC-01,riscv_regress
riscv,compliance_I-CSRRS-01,riscv_regress
riscv,compliance_I-CSRRW-01,riscv_regress
riscv,compliance_I-FENCE.I-01,riscv_regress
riscv,compliance_MULHU,riscv_regress
riscv,compliance_MULH,riscv_regress
riscv,compliance_DIVU,riscv_regress
riscv,compliance_MULHSU,riscv_regress
riscv,compliance_REMU,riscv_regress
riscv,compliance_MUL,riscv_regress
riscv,compliance_DIV,riscv_regress
riscv,compliance_REM,riscv_regress
riscv,compliance_C-OR,riscv_regress
riscv,compliance_C-ANDI,riscv_regress
riscv,compliance_C-SRLI,riscv_regress
riscv,compliance_C-SW,riscv_regress
riscv,compliance_C-J,riscv_regress
riscv,compliance_C-ADDI4SPN,riscv_regress
riscv,compliance_C-ADDI,riscv_regress
riscv,compliance_C-JR,riscv_regress
riscv,compliance_C-SUB,riscv_regress
riscv,compliance_C-JAL,riscv_regress
riscv,compliance_C-LWSP,riscv_regress
riscv,compliance_C-LI,riscv_regress
riscv,compliance_C-ADDI16SP,riscv_regress
riscv,compliance_C-BEQZ,riscv_regress
riscv,compliance_C-ADD,riscv_regress
riscv,compliance_C-BNEZ,riscv_regress
riscv,compliance_C-SWSP,riscv_regress
riscv,compliance_C-SLLI,riscv_regress
riscv,compliance_C-LW,riscv_regress
riscv,compliance_C-LUI,riscv_regress
riscv,compliance_C-SRAI,riscv_regress
riscv,compliance_C-AND,riscv_regress
riscv,compliance_C-XOR,riscv_regress
riscv,compliance_C-JALR,riscv_regress
riscv,compliance_C-MV,riscv_regress
riscv,isr_sample,riscv_regress
riscv,coremark,riscv_regress
riscv,dhrystone21,riscv_regress
riscv,hello,riscv_regress
